### PR TITLE
Added DONE event for notification of when all pages have been fetched

### PR DESCRIPTION
**Pull request by dondreytaylor**
I added a done event which gets triggered when all nextPage's have been fetched. Created a tests folder to house any future tests. Also noticed that xml2js was missing when I did npm install, so I added it to the dependencies.

getReviews must be called recursively in order for the done event to be emitted as such: 

```
var appStoreReviewsModule = require('app-store-reviews');
var appStoreReviews = new appStoreReviewsModule();

appStoreReviews.on('nextPage', function(nextPage) {	 
    appStoreReviews.getReviews(nextPage['appId'], nextPage['country'], nextPage['nextPage']);
});

appStoreReviews.on('done', function(data) {	 
    console.log("DONE")
});

appStoreReviews.getReviews("1111710488", "us", 1);
```

### CODE REVIEW

**Comment by jcoynel** [comment]
Hi @dondreytaylor,

Thanks the PR. It looks like you've not branched off from the latest commit on the master branch, so some of your changes are conflicted and some have already been implemented.

screenshot 2018-07-08 at 10 06 49

**Comment by dondreytaylor** [comment]
You're welcome. Oh wow, I didn't even notice that. I'll go back and work off the most recent commit.

**Comment by dondreytaylor** [comment]
Just want to confirm, is this the most recent commit [b811cd8](https://github.com/jcoynel/app-store-reviews/commit/b811cd8c5cd844c7352ef6778ee46d5ea0a69283)?

**Comment by jcoynel** [comment]
Yes, b811cd8 is the latest commit.

**Comment by jcoynel** [comment]
Thanks for your pull request. Unfortunately, this project is no longer maintained.

**Pull request closed without merging**
